// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

import { Navigation } from "./navigation/Navigation";

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }

// interface RootLayoutProps {
//   children: React.ReactNode;
// }

export default function RootLayout({ children }: { children: JSX.Element }) {
  return (
    <html>
      <body>
        <Navigation />
        <main>{children}</main>
      </body>
    </html>
  );
}
